apiVersion: integration/v1
kind: Step
name: exec
version: 1
summary: Execute SSH commands on a remote server

description: |
  This step executes a series of SSH commands directly on a remote server.

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    required:
    - connection
    - username
    - on
    - input
    properties:
      connection:
        type: object
        required:
        - sshKey
        properties:
          sshKey:
            type: string
      username:
        type: string
      port:
        type: number
      knownHosts:
        type: string
      strictHostKeyChecking:
        type: boolean
      on:
        type: array
        minItems: 1
        uniqueItems: true
        items:
          anyOf:
          - type: string
            format: hostname
          - type: string
            format: ipv4
          - type: string
            format: ipv6
      input:
        type: array
        items:
          type: string
        minItems: 1

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/exec
