apiVersion: integration/v1
kind: Step
name: ssh-step-exec
version: 1
summary: Execute SSH commands on a remote server

description: |
  Executes a series of SSH commands directly on a remote server.

schemas:
  spec:
    source: file
    file: spec.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/ssh-step-exec

examples:
- summary: Exec SSH command
  content:
    apiVersion: v1
    kind: Step
    name: ssh
    image: relaysh/ssh-step-exec
    spec:
      connection: ${connections.ssh.my-ssh-connection}
      username: ${parameters.username}
      port: 22 # defaults to 22
      knownHosts: |
        ${secrets.knownHosts}
      # or
      #strictHostKeyChecking: false
      on:
      - ${parameters.hostname}
      input:
      - ${parameters.command}
